name = "pauldoldendotcom"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
main = ".svelte-kit/cloudflare/_worker.js"

[assets]
directory = ".svelte-kit/cloudflare"
binding = "ASSETS"
